# Iteration
* for x in np.nditer(arr):


In [20]:
import numpy as np
arr1d = np.arange(1,11)
print(arr1d)

# iteration
for i in np.nditer(arr1d):
    print(i)

arr2d = np.arange(21,31).reshape(2,5)
print(arr2d)

# iteration in 2D array
for i in np.nditer(arr2d):
    print(i * 2)


[ 1  2  3  4  5  6  7  8  9 10]
1
2
3
4
5
6
7
8
9
10
[[21 22 23 24 25]
 [26 27 28 29 30]]
42
44
46
48
50
52
54
56
58
60


# Read and Write
* for i in np.nditer(arr, op-flags = ['readwrite'])

In [21]:
for x in np.nditer(arr1d, op_flags = ['readwrite']):
    x[...] = x *2
    print(x)
print(arr1d)


# read-write in 2D array
for s in np.nditer(arr2d, op_flags = ['readwrite']):
    s[...] = s * 1/2
print(arr2d)

2
4
6
8
10
12
14
16
18
20
[ 2  4  6  8 10 12 14 16 18 20]
[[10 11 11 12 12]
 [13 13 14 14 15]]


# Iteration with index
* for index,value in np.ndenumerate(a):
    print(index,value)

In [32]:
print("\n-v^v-v^v-In 1D Array-v^v-v^v-\n")
for index,value in np.ndenumerate(arr1d):
    print("index = ",index," value = ",value)

print("\n-v^v-v^v-In 2D Array-v^v-v^v-\n")
print(arr2d)
for i,v in np.ndenumerate(arr2d):
    print("index = ",i," value = ",v)



-v^v-v^v-In 1D Array-v^v-v^v-

index =  (0,)  value =  2
index =  (1,)  value =  4
index =  (2,)  value =  6
index =  (3,)  value =  8
index =  (4,)  value =  10
index =  (5,)  value =  12
index =  (6,)  value =  14
index =  (7,)  value =  16
index =  (8,)  value =  18
index =  (9,)  value =  20

-v^v-v^v-In 2D Array-v^v-v^v-

[[10 11 11 12 12]
 [13 13 14 14 15]]
index =  (0, 0)  value =  10
index =  (0, 1)  value =  11
index =  (0, 2)  value =  11
index =  (0, 3)  value =  12
index =  (0, 4)  value =  12
index =  (1, 0)  value =  13
index =  (1, 1)  value =  13
index =  (1, 2)  value =  14
index =  (1, 3)  value =  14
index =  (1, 4)  value =  15


In [33]:
print("\n-v^v-v^v-In 3D Array-v^v-v^v-\n")
arr3d = np.arange(20,40).reshape(2,2,5)
for i1,v1 in np.ndenumerate(arr3d):
    print("index = ",i1,"value = ",v1)



-v^v-v^v-In 3D Array-v^v-v^v-

index =  (0, 0, 0) value =  20
index =  (0, 0, 1) value =  21
index =  (0, 0, 2) value =  22
index =  (0, 0, 3) value =  23
index =  (0, 0, 4) value =  24
index =  (0, 1, 0) value =  25
index =  (0, 1, 1) value =  26
index =  (0, 1, 2) value =  27
index =  (0, 1, 3) value =  28
index =  (0, 1, 4) value =  29
index =  (1, 0, 0) value =  30
index =  (1, 0, 1) value =  31
index =  (1, 0, 2) value =  32
index =  (1, 0, 3) value =  33
index =  (1, 0, 4) value =  34
index =  (1, 1, 0) value =  35
index =  (1, 1, 1) value =  36
index =  (1, 1, 2) value =  37
index =  (1, 1, 3) value =  38
index =  (1, 1, 4) value =  39


# Random Module:
* np.random.rand()

In [36]:
print("\n-v^v-v^v-For Folating values-v^v-v^v-\n")
print(np.round(np.random.rand(1,6),3))
print(np.round(np.random.rand(),1))


-v^v-v^v-For Folating values-v^v-v^v-

[[0.932 0.374 0.965 0.848 0.792 0.528]]
0.0


* np.random.randint(low,high) -> return interger values 

In [ ]:
print(np.ceil(np.random.rand()))
print(np.random.randint(2,20,(3,2,4))) # important
print(np.random.randint(23,56,(3,4,7))) 

1.0
[[[15 19 17  4]
  [18  5  9  5]]

 [[ 3 16 19 15]
  [ 6 12  9 13]]

 [[ 5 10  2  7]
  [17 12 16  4]]]
[[[47 31 29 30 36 47 38]
  [37 26 29 50 38 42 39]
  [40 48 32 48 32 24 40]
  [40 24 51 27 29 34 37]]

 [[51 35 46 49 32 46 37]
  [24 24 46 34 30 27 41]
  [40 46 32 30 52 40 41]
  [24 33 35 34 34 34 32]]

 [[31 36 51 54 24 34 44]
  [34 24 25 28 46 46 46]
  [28 53 32 33 43 46 45]
  [48 36 47 35 47 24 55]]]


* np.random.randn(low,high)

In [66]:
print(np.abs(np.random.randn(3,2,5)))

[[[0.05028237 0.01475077 0.09238283 0.44419816 1.51724231]
  [0.85197777 1.38837552 0.33068453 0.84690921 0.86455375]]

 [[0.72317428 0.06091814 0.42549558 0.83677943 1.44592338]
  [0.4750422  0.18334357 0.64261434 1.8221868  0.5464683 ]]

 [[0.90417598 1.73000578 0.88954867 0.52716286 0.35923715]
  [0.23740442 0.49330134 1.50066252 1.80506564 0.66972072]]]


In [ ]:
arr4d = np.array([0.25,8.14,3.271,-10.1])
print(arr4d)
print(np.abs(np.round(arr4d)))


[  0.25    8.14    3.271 -10.1  ]
[ 0.  8.  3. 10.]
[1.44 6.77 9.  ]


# Random Sampaling
* np.random.choice(array,size)
* np.random.suffle(array,size)

In [ ]:
print(np.random.choice(arr1d,size = 2))
print(np.random.choice(arr2d, size = 1))  

[18 20]


ValueError: a must be 1-dimensional

In [102]:
np.random.shuffle(arr1d)
print(arr1d)
np.random.shuffle(arr2d)
print(arr2d)

[14 18 20  2 12 16  6  4 10  8]
[[10 11 11 12 12]
 [13 13 14 14 15]]


In [ ]:
np.random.seed(3)
print(np.random.randint(2,20))
print('\n \n')
print(np.random.randint(2,20))

12

 

5


In [115]:
np.random.seed(3)
print(np.random.randint(2,20))

12


In [120]:
print(np.random.randint(2,20))

17


In [121]:
np.random.seed(3)
print(np.random.randint(2,20))
print('\n \n')
print(np.random.randint(2,20))

12

 

5


In [122]:
print('\n \n')
np.random.seed(3)
print(np.random.randint(2,20))


 

12


In [123]:
print(np.random.randint(2,20,(3,2,4)))

[[[ 5 10  2 12]
  [13 11 12  8]]

 [[ 2 14  9 16]
  [19  4  4  3]]

 [[ 7 10 16  3]
  [12  9 13  3]]]
