In [8]:
import numpy as np
arr1 = np.arange(1,21,2)
arr2 = np.linspace(1,21,10)
print(arr1.size == arr2.size)


True


In [29]:
farr = np.array([1.4,2.5,3.1,3.9,4.6])
iarr = farr.astype(np.int32)
print(iarr)


[1 2 3 3 4]


In [32]:
zarr = np.zeros((3,4))
print(zarr.astype(np.int32))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [33]:
array = np.arange(1,25).reshape(2,3,4)
print(array)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [52]:
print(array[:,-1,:])

[[ 9 10 11 12]
 [21 22 23 24]]


In [75]:
arr1d = np.arange(1,21)
print(arr1d[::-2])
print(arr1d)

[20 18 16 14 12 10  8  6  4  2]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [90]:
arr3 = np.arange(1,26).reshape(5,5)
r = [0, 2, 4]
c = [1, 3, 0]
arr5 = arr3[r,c]
print(arr5)

[ 2 14 21]


In [1]:
rr = np.arange(1,4).reshape(3,1)
tt = np.arange(1,5).reshape(1,4)
print(rr,'\n',tt)
print(np.add(rr,tt))

NameError: name 'np' is not defined