In [2]:
import numpy as np
arr1 = np.random.randint(1,11,4).reshape(2,2)

arr2 = np.random.randint(1,11,4).reshape(2,2)
print(arr1,"\n",arr2)
print(np.dot(arr1,arr2))

[[9 5]
 [6 4]] 
 [[7 5]
 [9 3]]
[[108  60]
 [ 78  42]]


In [3]:
print(np.matmul(arr1,arr2))

[[108  60]
 [ 78  42]]


In [4]:
print(np.shape(arr1))
print(np.size(arr1))
print(np.ndim(arr1))
print(arr1.dtype)
arr1 = arr1.astype(np.int32)
print(arr1.dtype)

(2, 2)
4
2
int64
int32


In [5]:
print(np.empty(6).reshape(2,3))

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
print(np.zeros(5))
print(np.ones(6))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]


In [7]:
print(np.arange(1,11))
print(np.linspace(1,11,10))

[ 1  2  3  4  5  6  7  8  9 10]
[ 1.          2.11111111  3.22222222  4.33333333  5.44444444  6.55555556
  7.66666667  8.77777778  9.88888889 11.        ]


In [8]:
print(np.zeros(3).dtype)

float64


In [9]:
arr3 = np.random.randint(23,66,18)
print(arr3)
print(np.sort(arr3)[-2])

[30 55 34 43 31 52 47 30 43 56 53 37 50 52 33 54 48 60]
56


In [8]:
import numpy as np
arr1 = np.random.randint(1,50,10)
print(arr1)
print(np.average(arr1))
print(np.median(arr1))
print(np.mean(arr1))
print(np.var(arr1))
print(np.prod(arr1))

[18 37 29 24 23 37  1 14 26 31]
24.0
25.0
24.0
108.2
4451189730624


In [ ]:
print(np.__version__)