In [2]:
import numpy as np
a = np.array([10,20,40])
print(a.dtype)

int64


In [3]:
b = np.array([10.23,2.34,4.45])
print(b.dtype)

float64


In [4]:
c = np.array(['Shubham','Raj'])
print(c.dtype)
print(c.size)
print(c.itemsize)

<U7
2
28


In [6]:
x = np.array(["Hello"],dtype = "U3")
print(x)

['Hel']


In [13]:
y = np.array([-128],dtype = np.int8)
print(y)

[-128]


In [17]:
fl = np.array([12.33,34.5,65.67],dtype = np.int16)
print(fl)


[12 34 65]


In [21]:
ff = a.astype(float)
print(ff)
print(a)

[10. 20. 40.]
[10 20 40]


In [28]:
dd = np.array([10,23,42,3,51,4,6,75,7,98,33,565])
print(dd[:7:2])

[10 42 51  6]


In [29]:
print(dd[5:8])

[ 4  6 75]


In [30]:
print(dd[2:6])

[42  3 51  4]


In [32]:
print(dd[:7:-1])

[565  33  98   7]


In [33]:
print(dd[::-1])

[565  33  98   7  75   6   4  51   3  42  23  10]


In [44]:
arr2d = np.array([[1,2,3,4],
          [4,5,6,8],
          [66,7,55,78],
          [19,29,78,90]])
print(arr2d[:2, 2:])
print(arr2d[::-1,::-1])

[[3 4]
 [6 8]]
[[90 78 29 19]
 [78 55  7 66]
 [ 8  6  5  4]
 [ 4  3  2  1]]


In [43]:
er = arr2d.astype(str)
print(er)

[['1' '2' '3' '4']
 ['4' '5' '6' '8']
 ['66' '7' '55' '78']
 ['19' '29' '78' '90']]
