# Linear Algebra

* Dot Product:-

In [ ]:
import numpy as np
arr1d = np.arange(5)
arr1d = np.delete(arr1d,0)
print(arr1d)

# For 1D array.
arr1d2 = np.array([10,12,13])
arr1d3 = np.array([2,4,6])
print(np.dot(arr1d2,arr1d3))

print(arr1d2@arr1d3)

# For 2D array.
arr2d = np.arange(1,9)
arr2d3 = arr2d.reshape(2,4)
arr2d2 = np.array([[12,33],[4,5],[45,66],[89,4]])
print(arr2d2.shape,arr2d.shape)
print(arr2d2.ndim,arr2d.ndim)
print(arr2d2@arr2d3)
print(np.dot(arr2d2,arr2d3))



[1 2 3 4]
146
146
-----------
[[[ 88  94]
  [214 229]]

 [[484 508]
  [664 697]]]


In [42]:
# For 3D array.
arr3d = np.arange(1,13).reshape(2,2,3)
arr3d2 = np.arange(12,24).reshape(2,3,2)
print(arr3d)
print('.')
print(arr3d2)
print("-----------")
print(arr3d@arr3d2)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
.
[[[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]
-----------
[[[ 88  94]
  [214 229]]

 [[484 508]
  [664 697]]]


In [53]:
e = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
f = np.array([[[9,8,7],[6,5,4],[3,2,1]]])
print(e@f)
print(np.dot(e,f))
print(np.matmul(e,f))

[[[ 30  24  18]
  [ 84  69  54]
  [138 114  90]]]
[[[[ 30  24  18]]

  [[ 84  69  54]]

  [[138 114  90]]]]
[[[ 30  24  18]
  [ 84  69  54]
  [138 114  90]]]


* np.matmul(a,b)

In [ ]:
# 1D array: 
print(np.matmul(arr1d3,arr1d2))

# 2D array: 
print(np.matmul(arr2d2,arr2d3))

# 3D array: 
print(np.matmul(arr3d,arr3d2))


146
[[177 222 267 312]
 [ 29  38  47  56]
 [375 486 597 708]
 [109 202 295 388]]
[[[ 88  94]
  [214 229]]

 [[484 508]
  [664 697]]]


# Determination
* np.linalg.det(arr)

In [ ]:
# Determination in 3D
arr3de = np.array([[[12,44,34],
                    [45,77,89],
                    [46,90,23]]])
print(np.linalg.det(arr3de))

[77000.]


# Inverse
* np.linalg.inv(arr)

In [56]:
print(np.linalg.inv(arr3de))

[[[-0.08102597  0.0265974   0.01685714]
  [ 0.03972727 -0.01672727  0.006     ]
  [ 0.0065974   0.01225974 -0.01371429]]]


# Solve Linear Equation
* np.linag.solve(arr1,arr2)

In [65]:
# 2D array:

A = np.array([[1,1],[2,1]])
B = np.array([5,1])
# print(np.linalg.solve(A,B))

# 3D array: 
C = np.array([23,44,56])
print(np.linalg.solve(arr3de,C))

# 1D array:
E = np.array([6,0])
print(np.linalg.solve(A,E))

[[ 0.25068831  0.51372727 -0.07683117]]
[-6. 12.]
