In [730]:
import numpy as np
arr = np.random.randint(1,100,(6,6))
print(arr)

[[64  5 83 58 15 66]
 [94 78 21 57 92 27]
 [51 23 65 42 77 75]
 [71 58 53 83 28 97]
 [72 14 47 26 75 31]
 [86 52 51 67 93 10]]


In [731]:
median = np.median(arr)
print(median)

58.0


In [732]:
# if np.any(arr[:] % 2 == 0):
#     arr = np.sort(arr)
# print(arr)
# # print(arr[1:4])


In [733]:
import numpy as np

arr = np.random.randint(1, 100, (6, 6))
print("Original array:")
print(arr)
max_indices = np.argmax(arr, axis=1)
arr[np.arange(arr.shape[0]), max_indices] = 0

print("\nArray after replacing maximum elements with 0:\n")
print(arr)


Original array:
[[39 22 35  3 99  5]
 [50 42 16 81 40 68]
 [50  3 68 89 14 44]
 [84 94 65 55 36 23]
 [31 97 68 56 90 27]
 [ 6 39  7 43 73 31]]

Array after replacing maximum elements with 0:

[[39 22 35  3  0  5]
 [50 42 16  0 40 68]
 [50  3 68  0 14 44]
 [84  0 65 55 36 23]
 [31  0 68 56 90 27]
 [ 6 39  7 43  0 31]]


In [734]:
min_indices = np.argmin(arr, axis=0)
arr[np.arange(arr.shape[0]), min_indices] = -1
print(arr)

[[39 22 35  3  0 -1]
 [50 42 16 -1 40 68]
 [50  3 68  0 14 -1]
 [84 -1 65 55 36 23]
 [-1  0 68 56 90 27]
 [-1 39  7 43  0 31]]


In [735]:
# index = np.argwhere(arr % 2 == 0). # My code
even_rows = np.any(arr % 2 == 0, axis=1)
arr[even_rows] = np.sort(arr[even_rows], axis=1)
print(arr)

[[-1  0  3 22 35 39]
 [-1 16 40 42 50 68]
 [-1  0  3 14 50 68]
 [-1 23 36 55 65 84]
 [-1  0 27 56 68 90]
 [-1  0  7 31 39 43]]


In [736]:
# Teacher's code
arr[0::2] = np.sort(arr[0::2],axis = 1)
print(arr)

[[-1  0  3 22 35 39]
 [-1 16 40 42 50 68]
 [-1  0  3 14 50 68]
 [-1 23 36 55 65 84]
 [-1  0 27 56 68 90]
 [-1  0  7 31 39 43]]


In [737]:
np.save(
    "arr.npy",
    arr
)
x = np.load("arr.npy")
print(x)

[[-1  0  3 22 35 39]
 [-1 16 40 42 50 68]
 [-1  0  3 14 50 68]
 [-1 23 36 55 65 84]
 [-1  0 27 56 68 90]
 [-1  0  7 31 39 43]]


In [738]:
a = np.random.randint(1,100,(6,6))