## File Handling:
* It's used when user wants to store arrays permanently and use them later without recreating them 

### save():
* It saves a single numpy array to a binary file with a .npy extention.

### savez():
* It saves multiple arrays to a single compressed file wiht a .npz extention. It's perfect when we have related arrays those are belong togater. (putting multiple related file into a zipfolder).

In [2]:
import numpy as np
name = np.array(['x','y','z','a'])
age = np.array([20,15,16,15,21])
np.save("age.npy",age) 

In [23]:
import numpy as np
class file_hadeling:
    def my_file_practice(self):
        name = np.array(['x','y','z','a'])
        age = np.array([20,15,16,15,21])
        np.save("age.npy",age)    
fh1 = file_hadeling()
fh1.my_file_practice()
    

In [24]:
marks = np.array([56,78,90,42])
np.savez(
    'student.npz',
    age = age,
    name = name,
    marks = marks
)
print("Wo file ban geya")

Wo file ban geya


## Load:
* Load is used to read arrays those were previusly saved in same our file.

In [26]:
x = np.load("name.npy")
print(np.load('student.npz')['age'])
# print(vv['age'])
print(x)


[20 15 16 15 21]
['x' 'y' 'z' 'a']


In [3]:
math = np.random.randint(67,89,10)
physics = np.random.randint(90,99,10)
bio = np.random.randint(45,78,10)
print(math,'\n',physics,'\n',bio)
np.savez(
    'Sujects.npz',
    math = math,
    physics = physics,
    bio = bio
)
print("File created successfully.")

[73 77 78 77 83 88 86 87 84 74] 
 [92 91 96 96 96 95 97 94 96 98] 
 [74 64 48 61 66 67 71 74 59 70]
File created successfully.


In [11]:
print(np.load('Sujects.npz')['math'] + np.load('Sujects.npz')['bio'])
print(np.median(np.load('Sujects.npz')['physics']))

[147 141 126 138 149 155 157 161 143 144]
96.0
