In [30]:
#Nagetive indexing:

import numpy as np
arr1d = np.array([23,44,56,12]);

arr2d = np.array([[12,20,30],
                [40,50,60],
                [80,90,100]]);

arr3d = np.array([[[22,23,45],[13,26,77],[11,89,90]],
                [[12,78,23],[23,44,78],[35,67,89]]]);

print(arr1d[-1]);
print(arr1d[-2]);

print(arr2d[-1]);
print(arr2d[-1,-1]);
print(arr2d[[-1],[-1]]);

print(arr3d[-1,-2,-1]);
print(arr3d[-1]);
print(arr3d[1:3:])

12
56
[ 80  90 100]
100
[100]
78
[[12 78 23]
 [23 44 78]
 [35 67 89]]
[[[12 78 23]
  [23 44 78]
  [35 67 89]]]


In [ ]:
# Boolean indexing:

marks = np.array([60,90,70,80,89,99]);
score = marks>70
print(score)

print([arr3d>40])

[False  True False  True  True  True]
[array([False,  True, False,  True,  True,  True])]
[array([[[False, False,  True],
        [False, False,  True],
        [False,  True,  True]],

       [[False,  True, False],
        [False,  True,  True],
        [False,  True,  True]]])]


In [38]:
# Fancy Indexing:

index_list = [1,4,3,5]

print(marks[index_list])

index_list2 = [1,0,2]
print(arr2d[index_list2])

[90 89 80 99]
[[ 40  50  60]
 [ 12  20  30]
 [ 80  90 100]]


In [ ]:
# NUMPY OPERATION: 

x = np.array([10,20,30,40])
y = np.array(['2','3','4','5'], dtype=np.int32)

# Arithmetic operation:
print("Addition: ", x+y)
print("Subtraction: ", x-y)
print("Multiplecation: ", x*y)
print("Division: ", x/y)
print("Floor Division: ", x//y)
print("modulo: ", x%y)
print("Power: ", x**(1/y))

Addition:  [12 23 34 45]
Subtraction:  [ 8 17 26 35]
Multiplecation:  [ 20  60 120 200]
Division:  [5.         6.66666667 7.5        8.        ]
Floor Division:  [5 6 7 8]
modulo:  [0 2 2 0]
Power:  [3.16227766 2.71441762 2.34034732 2.09127911]


In [53]:
# Comparision operation:
print("Equality: ", x==y)
print("Greater than: ", x>y)
print("Less than: ", x<y)
print("Not equal: ", x!=y)
print("Greater than equal: ", x>=y)
print("Less than equal: ", x<=y)


Equality:  [False False False False]
Greater than:  [ True  True  True  True]
Less than:  [False False False False]
Not equal:  [ True  True  True  True]
Greater than equal:  [ True  True  True  True]
Less than equal:  [False False False False]


In [8]:
print(int('1013242322',33))

46458060338516
