In [2]:
import numpy as np
arr = np.array([16,34,64,75])
print(arr)

[16 34 64 75]


In [43]:
# 2D array:
arr2d = np.array([['add','b','c'],['d','ettr','f']])
print(arr2d)

[['add' 'b' 'c']
 ['d' 'ettr' 'f']]


In [4]:
# 3D array:
arr3d = np.array([[[1,2,3,4],[2,3,54,67],[11,54,76,89]],
                  [[12,44,65,78],[65,67,87,33],[23,45,12,13]],
                  [[30,54,21,43],[543,67,80,81],[122,554,789,10]]])
print(arr3d)


[[[  1   2   3   4]
  [  2   3  54  67]
  [ 11  54  76  89]]

 [[ 12  44  65  78]
  [ 65  67  87  33]
  [ 23  45  12  13]]

 [[ 30  54  21  43]
  [543  67  80  81]
  [122 554 789  10]]]


In [13]:
# One's array:
print(np.ones(5))
# 2d ones array:
print(np.ones((2,3)))
# 3d ones array:
print(np.ones((3,3)))

[1. 1. 1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# Zero's array:
print(np.zeros(5))
# 2d zeros array:
print(np.zeros((2,3)))
# 3d zeros array:
print(np.zeros((3,3)))

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [32]:
# Empty array:
print(np.empty(3))
# 2d empty array:
emp2d = np.empty((2,3))
print(emp2d)
# 3d empty array:
emp3d = np.empty((3,4))
print(emp3d)

[3. 2. 1.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [28]:
print(arr.shape)
print(arr2d.shape)
print(arr3d.shape)

(4,)
(2, 3)
(3, 3, 4)


In [35]:
print(arr.size)
print(arr2d.size)
print(arr3d.size)

4
6
36


In [36]:
print(arr.ndim)
print(arr2d.ndim)
print(arr3d.ndim)

1
2
3


In [ ]:
print(arr.dtype)
print(arr2d.dtype)
rr = np.array([[2.3,4.5,5.6],[2.4,3.5,7.9]])
print(rr.dtype)

int64
<U4
float64


In [56]:
print(arr.itemsize)
print(arr2d.itemsize)
print(rr.itemsize)


8
16
8


In [59]:
print(arr.nbytes)
print(arr2d.nbytes)
print(rr.nbytes)

32
96
48


In [53]:

ff = np.array(['d','t','r'],dtype=object)
print(ff.dtype)


object


In [34]:
gg = np.empty((3,5))
gg

array([[0.        , 0.        , 0.4472136 , 0.0531494 , 0.18257419],
       [0.4472136 , 0.2125976 , 0.36514837, 0.4472136 , 0.4783446 ],
       [0.54772256, 0.4472136 , 0.85039041, 0.73029674, 0.4472136 ]])