In [ ]:
import numpy as np
arr1d = np.arange(10)
print(arr1d)
arr1d2 = np.array([21,33,4,55,6,77,8,78,90,21])
arr2d = arr1d.reshape(2,5)
print(arr2d)



[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


# Array manipulation
#### Array joining
----
* np.concatenate((a,b),axis = 0)

In [5]:
catarr = np.concat((arr1d,arr1d2),axis = 0)
print(catarr)

[ 0  1  2  3  4  5  6  7  8  9 21 33  4 55  6 77  8 78 90 21]


In [12]:
arr2d2 = np.array([[22,56,78,33,67],[12,13,15,67,87]])
print(arr2d,"\n",arr2d2)
p = np.concatenate((arr2d,arr2d2),axis = 0)
p1 = np.concatenate((arr2d,arr2d2),axis = 1)
print(p1,"\n\n",p)

[[0 1 2 3 4]
 [5 6 7 8 9]] 
 [[22 56 78 33 67]
 [12 13 15 67 87]]
[[ 0  1  2  3  4 22 56 78 33 67]
 [ 5  6  7  8  9 12 13 15 67 87]] 

 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [22 56 78 33 67]
 [12 13 15 67 87]]


* np.stack(())

In [14]:
print(np.stack((arr1d,arr1d2)))

[[ 0  1  2  3  4  5  6  7  8  9]
 [21 33  4 55  6 77  8 78 90 21]]


In [ ]:
print(np.hstack((arr1d,arr1d2)))
print(np.vstack((arr1d,arr1d2)))


[ 0  1  2  3  4  5  6  7  8  9 21 33  4 55  6 77  8 78 90 21]
[[ 0  1  2  3  4  5  6  7  8  9]
 [21 33  4 55  6 77  8 78 90 21]]


* 2D implemention in np.hstack(())

In [22]:
print(np.hstack((arr2d,arr2d2)))
print(np.vstack((arr2d,arr2d2)))

[[ 0  1  2  3  4 22 56 78 33 67]
 [ 5  6  7  8  9 12 13 15 67 87]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [22 56 78 33 67]
 [12 13 15 67 87]]


#### Spliting Array
* np.split(array_name,amount)

In [ ]:
print(np.split(arr1d,5))
print(np.split(arr1d,2))


[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]
[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


* split() function in 2D array

In [ ]:
print(np.split(arr2d,2))


[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]
[array([0, 1, 2]), array([3, 4])]


In [ ]:
print(np.array_split(arr1d,7))
print(np.array_split(arr1d2,6))
# --
print(np.array_split(arr2d[0],2))

[array([0, 1]), array([2, 3]), array([4, 5]), array([6]), array([7]), array([8]), array([9])]
[array([21, 33]), array([ 4, 55]), array([ 6, 77]), array([ 8, 78]), array([90]), array([21])]


In [41]:
print(np.array_split(arr2d,2))

[array([[0, 1, 2, 3, 4]]), array([[5, 6, 7, 8, 9]])]


# Inserting Element
* np.insert()


In [42]:
print(np.insert(arr1d,4,80))

[ 0  1  2  3 80  4  5  6  7  8  9]


In [46]:
print(np.insert(arr2d2,[1],99))
print(arr2d2)

[22 99 56 78 33 67 12 13 15 67 87]
[[22 56 78 33 67]
 [12 13 15 67 87]]


## Multiple values inserting
* np.append()

In [48]:
print(np.append(arr1d,(233,555,678)))
print(np.append(arr2d2,(333,788,900)))

[  0   1   2   3   4   5   6   7   8   9 233 555 678]
[ 22  56  78  33  67  12  13  15  67  87 333 788 900]


## Deleting element
* np.delete()

In [49]:
print(np.delete(arr1d,0))

[1 2 3 4 5 6 7 8 9]


In [51]:
print(np.delete(arr2d,2,1))

[[0 1 3 4]
 [5 6 8 9]]
