In [1]:
import numpy as np
roll = np.random.randint(34,56,20)
np.savetxt(
    'roll.txt',
    roll,
    fmt = '%d'
)

In [2]:
np.savetxt(
    'roll_str.txt',
    roll,
    fmt = '%s'
)

In [3]:
str_roll = np.loadtxt(
    'roll_str.txt',
    dtype = str
)

In [5]:
print(str_roll)
np.savetxt(
    'ssttrr_roll.txt',
    str_roll,
    fmt = '%s'
)

['47' '52' '50' '36' '37' '37' '55' '53' '41' '41' '42' '51' '55' '47'
 '38' '51' '54' '37' '41' '50']


In [9]:
print(str_roll[1:4])
print(int(str_roll[5]))

['52' '50' '36']
37


In [22]:
arr3r = np.random.randint(12,99,10)
np.savetxt(
    'marks1.txt',
    arr3r,
    delimiter = ',',
    fmt = '%d'
)
ttt = np.loadtxt(
  'marks1.txt',
#   delimiter = ',',
  dtype = int  

)
print(ttt)

[49 78 41 76 45 21 98 52 96 13]


In [54]:
arr = np.array(['print("Hello world")print(23+45)'])
np.savetxt(
    'ar.py',
    arr,
    delimiter = ';',
    fmt = "%s"
)
run = np.loadtxt(
    'ar.py',
    delimiter = ';',
    dtype = str
)

In [58]:
print(arr)
print(arr.shape,"\n",run.size)

['print("Hello world")print(23+45)']
(1,) 
 1


In [56]:
print(np.array(["Sudip Barman"]).shape)


(1,)


In [49]:
arr1 = np.array(['print("Heefrger lloworld");priggnt(23+45)'])
print(arr1.shape)

(1,)


In [36]:
arrC = np.array(['print("Shubham Jana")','print(332/4)'])
np.savetxt(
    's.py',
    arrC,
    fmt = "%s"
)
print(arrC)

['print("Shubham Jana")' 'print(332/4)']


In [38]:
Code_run = np.loadtxt(
    's.py',
    delimiter=';',
    dtype = str
)

In [39]:
print(Code_run)

['print("Shubham Jana")' 'print(332/4)']


In [42]:
arr2d = np.random.randint(23,78,10).reshape(2,5)
print(arr2d)
np.savetxt(
    '2Darray.txt',
    arr2d,
    fmt = "%d"
)
oo = np.loadtxt(
    '2Darray.txt',
    dtype = int
)

[[43 60 34 36 57]
 [50 23 37 32 65]]


In [43]:
print(run)

['print("Hello' 'world");print(23+45)']


In [44]:
print(run.shape)

(2,)


In [45]:
names = np.array(['Shubham Jana','Sudeep Bera'])
print(names.shape)
print(names.size)

(2,)
2
