In [ ]:
# Aggregate function
import numpy as np
arr = np.arange(20)
print(arr)

# np.sum()
print(np.sum(arr))
# np.average()
print(np.average(arr))
# np.absolute()
print(np.absolute(arr))
flo = np.array([12.44,5.76,-33.67,-78.90])
print(np.absolute(flo))
arr2d = arr.reshape(5,4)
print(arr2d)
# axis-based operations
print(np.sum(arr2d, axis = 1)) # while axis = 1 it returns the sum of the all elements of a single row 

print(np.sum(arr2d, axis = 0)) # while axis = 0 it returns the sum of the all elements of a single column




[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
190
9.5
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[12.44  5.76 33.67 78.9 ]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[ 6 22 38 54 70]
[40 45 50 55]


### Rounding functions 

* np.round() 

In [7]:
float_arr = np.array([12.1113,34.555,3.456,6.789,55.675,-9.084,-19.9,-3.77])
print(np.round(float_arr,1))


[ 12.1  34.6   3.5   6.8  55.7  -9.1 -19.9  -3.8]


* np.floor() 

In [9]:
print(np.floor(float_arr))

[ 12.  34.   3.   6.  55. -10. -20.  -4.]


* np.ceil()

In [10]:
print(np.ceil(float_arr))

[ 13.  35.   4.   7.  56.  -9. -19.  -3.]


### Logarithmic functions 
* np.log()
* np.log10()
* np.log2()
* np.log().round(n)

In [18]:
larr = [1,3.4,7,10,100,100]
print(np.log(larr))
print(np.log10(larr))
print(np.log2(larr))
print(np.log2(larr).round(1))
print(np.log1p(larr).round(2))

[0.         1.22377543 1.94591015 2.30258509 4.60517019 4.60517019]
[0.         0.53147892 0.84509804 1.         2.         2.        ]
[0.         1.76553475 2.80735492 3.32192809 6.64385619 6.64385619]
[0.  1.8 2.8 3.3 6.6 6.6]
[0.69 1.48 2.08 2.4  4.62 4.62]


### Trignometric 
* np.sin()
* np.cos()
* np.tan()
* np.radians()
* np.arcsin()
* np.arccos()
* np.arctan()
* np.degrees()

In [42]:
red = np.array([30,45,60,90])
red1 = np.array([0.199,0.8,0.4,0.72])
print(np.sin(red))
print(np.cos(red).round(2))
print(np.tan(red).round(2))
print(np.radians(red).round(3))
print(np.arcsin(red1).round(2))
print(np.degrees(np.arcsin(red1)).round(1))
print(np.degrees(np.arccos(red1)).round(1))
print(np.degrees(np.arctan(red1)).round(1))
theta = 30
tant = np.tan(30)
sint = np.sin(30)
cost = np.cos(30)

print(np.sin(np.degrees(90)))
print(((np.sin(theta))**2)+(np.cos(theta))**2)

if (tant == (sint/cost)):
    print("Thufaniiiii 😎")
else:
    print("Faaaaaa!")

[-0.98803162  0.85090352 -0.30481062  0.89399666]
[ 0.15  0.53 -0.95 -0.45]
[-6.41  1.62  0.32 -2.  ]
[0.524 0.785 1.047 1.571]
[0.2  0.93 0.41 0.8 ]
[11.5 53.1 23.6 46.1]
[78.5 36.9 66.4 43.9]
[11.3 38.7 21.8 35.8]
-0.9540914674728181
1.0
Thufaniiiii 😎
