In [23]:
# Universal operator
import numpy as np
print(np.add(2,3))
print(np.subtract(5,6))
print(np.multiply(2,9))
print(np.divide(8,2))
print(np.floor_divide(77.4,5.77))
a = np.array([1.9,2.54,6.1,4.5,5.9])
print(np.max(a))
print(np.min(a))
print(np.square(5))
print(np.sqrt(25))
print(np.abs(-9.7))
print(np.abs(7.9))
print(np.mean(a))
print(np.median(a))
print(np.std(a))
print(np.var(a))
print(np.mod(3,5))
print(np.power(a,3))

b = np.floor(a)
print(b.dtype)



5
-1
18
4.0
13.0
6.1
1.9
25
5.0
9.7
7.9
4.188
4.5
1.7108407289984653
2.926976
3
[  6.859     16.387064 226.981     91.125    205.379   ]
float64


In [ ]:
# .reshape() 
x = np.array([[12,33,45,67],
              [32,55,76,89],
              [16,17,19,90]])
print(np.shape(x))
y = x.reshape(2,6)
print(y)

(3, 4)
[[12 33 45 67 32 55]
 [76 89 16 17 19 90]]


In [29]:
arr = np.arange(0,12)
print(arr)
print(arr.reshape(3,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [32]:
print(np.resize(arr,[2,6]))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [37]:
bb = arr.reshape(3,4)
arree = arr.transpose()
print(bb.T)

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [38]:
print(np.expand_dims(bb,axis = 1))

[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]


In [39]:
print(np.squeeze(bb))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
